version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    volumes:
      # A dicionamos o arquivo init.sql para a pasta
      # /docker-entrypoint-initdb.d/init.sql, pois irá rodar o script
      # Na primeira vez que o container for executado
      # Já populando o banco de dados com os scripts sql inseridos no arquivo
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"

volumes:
  mysql-volume:
    driver: local