# Usa a imagem oficial do Postgres
FROM postgres:latest

# Define variáveis de ambiente
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=jhonatan123
ENV POSTGRES_DB=postgres

# Expõe a porta padrão do Postgres
EXPOSE 5432
